version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - overlay

  go-woker:
    container_name: goworker
    build:
      context: ./simple-go-worker
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - overlay
  
  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - overlay

  vue:
    container_name: vue
    build:
      context: ./vlille
    volumes:
      - ./vlille:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - overlay
networks:
  overlay: