version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  go-woker:
    build:
      context: ./simple-go-worker
    ports:
      - "8080:8080"
    depends_on:
      - redis